service: go-serverless
provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
  stage: dev

package:
  patterns:
    # inclue
    - bin/**
    # exclude
    # - '!tmp/**'

functions:
  hello:
    handler: bin/main # reference to main.go
  graph: # second function
    handler: bin/graphql # reference to graphql.go
    events: # event trigger
      - http:
          path: goserverlesslambda
          method: get
          cors: true
